# https://docs.astral.sh/ruff/configuration/
# https://docs.astral.sh/ruff/settings/
# https://docs.astral.sh/ruff/rules/
#
# To check option value:
# $ ruff config line-length
# $ ruff config lint.select

line-length = 120

[lint]
select = [
  "E4",
  "E7",
  "E9",
  # Pyflakes (F)
  "F",
  # isort (I)
  "I",
  # flake8-bugbear (B)
  "B"
]
