#!/bin/zsh

autoload -U compinit zrecompile

#zsh_cache=$HOME/.zsh/cache
#mkdir -p "$zsh_cache"

#compinit -d "$zsh_cache/zcomp"

for zshrc_snippet in "$HOME/.zsh/rc/S"[0-9][0-9]* ; do
    source "$zshrc_snippet"
done

if [ -f "/etc/zsh_command_not_found" ] ; then
    source /etc/zsh_command_not_found
fi
