gui:
  scrollHeight: 4
  nerdFontsVersion: "3"
  theme:
    lightTheme: true
  animateExplosion: false
  spinner:
    frames: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']
    rate: 100
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
  # Do not spawn a separate process when using GPG
  # https://github.com/jesseduffield/lazygit/discussions/3605#discussioncomment-9567079
  overrideGpg: true
  autoForwardBranches: none
notARepository: skip
keybinding:
  commits:
    moveDownCommit: '<c-n>'
    moveUpCommit: '<c-p>'
showNumstatInFilesView: true
customCommands:
  - key: '<c-d>'
    description: 'Show Difftastic for current commit'
    context: 'subCommits'
    command: 'git dshow "{{.SelectedLocalCommit.Sha}}"'
    output: terminal
  - key: '<c-d>'
    description: 'Show difft of current commit'
    context: 'files'
    command: 'git dft -- {{.SelectedFile.Name | quote}}'
    output: terminal
  - key: '<c-d>'
    description: 'Show difft of current commit'
    context: 'commitFiles'
    command: 'git dshow "{{.SelectedLocalCommit.Sha}}" -- {{.SelectedCommitFile.Name | quote}}'
    output: terminal
  - key: '<c-d>'
    description: 'Show difft of current commit'
    context: 'commits'
    command: 'git dshow "{{.SelectedLocalCommit.Sha}}"'
    output: terminal
  - key: 'I'
    description: 'Open in idea'
    context: 'files'
    command: 'idea {{.SelectedFile.Name | quote}}'
