---
gui:
  scrollHeight: 4
  nerdFontsVersion: "3"
  theme:
    lightTheme: true
  branchColors:
    'develop': '#ff2222'
  animateExplosion: false
  spinner:
    frames: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']
    rate: 100
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
  commitPrefixes:
    gazprom:
      pattern: "^(\\d+)-.*"
      replace: "feat: #$1 "
  # branchLogCmd: "git lg --color=always --no-merges --graph {{branchName}} --"
services:
  'git.technocom.tech': 'gitea:git.technocom.tech'
notARepository: skip
keybinding:
  commits:
    moveDownCommit: '<c-n>'
    moveUpCommit: '<c-p>'
customCommands:
  - key: '<c-d>'
    description: 'Show Difftastic for current commit'
    context: 'subCommits'
    command: 'git dshow "{{.SelectedLocalCommit.Sha}}"'
    subprocess: true
  - key: '<c-d>'
    description: 'Show difft of current commit'
    context: 'files'
    command: 'git dft -- {{.SelectedFile.Name | quote}}'
    subprocess: true
  - key: '<c-d>'
    description: 'Show difft of current commit'
    context: 'commitFiles'
    command: 'git dshow "{{.SelectedLocalCommit.Sha}}" -- {{.SelectedCommitFile.Name | quote}}'
    subprocess: true
  - key: '<c-d>'
    description: 'Show difft of current commit'
    context: 'commits'
    command: 'git dshow "{{.SelectedLocalCommit.Sha}}"'
    subprocess: true
  - key: 'I'
    description: 'Open in idea'
    context: 'files'
    command: 'idea {{.SelectedFile.Name | quote}}'
