[global]
target = "~/.local/bin"
upgrade_only = true

["rclone/rclone"]
asset_filters = [ "zip" ]

["restic/restic"]

["zyedidia/eget"]

["antonmedv/fx"]

["docker/compose"]
target = "~/.local/bin/docker-compose"

["jesseduffield/lazygit"]

["pypa/pipx"]

["akavel/up"]
asset_filters = [ "up" ]

["so-fancy/diff-so-fancy"]

["mvdan/sh"]
target = "~/.local/bin/shfmt"
