[global]
target = "~/.local/bin"
upgrade_only = true

["zyedidia/eget"]

["antonmedv/fx"]

["docker/compose"]
target = "~/.local/bin/docker-compose"

["jesseduffield/lazygit"]

["pypa/pipx"]

["akavel/up"]

["so-fancy/diff-so-fancy"]

["mvdan/sh"]
target = "~/.local/bin/shfmt"
