[global]
target = "~/.local/bin"
upgrade_only = true

["rclone/rclone"]
asset_filters = [ "zip" ]

["restic/restic"]

["zyedidia/eget"]

["antonmedv/fx"]

["mikefarah/yq"]
asset_filters = [ "tar.gz" ]
file = "yq_linux_amd64"
target = "~/.local/bin/yq"

["jarun/nnn"]
asset_filters = [ "nnn-nerd-static" ]
target = "~/.local/bin/nnn"

["docker/compose"]
target = "~/.local/bin/docker-compose"

["jesseduffield/lazygit"]

["sharkdp/bat"]

["pypa/pipx"]

["akavel/up"]
asset_filters = [ "up" ]

["so-fancy/diff-so-fancy"]

["mvdan/sh"]
target = "~/.local/bin/shfmt"
