[global]
target = "~/.local/bin"
upgrade_only = true

# Easily install prebuilt binaries from GitHub.
["zyedidia/eget"]

# n³ The unorthodox terminal file manager
["jarun/nnn"]
asset_filters = [ "nnn-nerd-static" ]
target = "~/.local/bin/nnn"

# A shell parser, formatter, and interpreter with bash support; includes shfmt
["mvdan/sh"]
target = "~/.local/bin/shfmt"

# Good-lookin' diffs. Actually… nah… The best-lookin' diffs. 🎉
["so-fancy/diff-so-fancy"]
